### ISSUE TITLE
로그인 회원 가입 기능 개발 - feature/auth

### ISSUE THREAD

**Issue by robert-min** [robert-min/langchain-chat-service#1]
## TODO

- [ ] DB 인프라 구축
  - [ ] PostgreSQL 테이블 생성
  - [ ] DB 스키마 설정

**Comment by robert-min** [comment]
```sql
-- user_account 테이블 생성
CREATE TABLE user_account (
    seq BIGSERIAL PRIMARY KEY,
    email VARCHAR(500) NOT NULL,
    password BYTEA NOT NULL,
    status BOOLEAN NOT NULL DEFAULT TRUE
);

-- user_account 테이블 삭제
DROP TABLE user_account;

```

**Comment by robert-min** [comment]
로그인 회원가입 없이 핵심 기능에 집중해서 서버 개발
